### ISSUE TITLE
Use mission file "DisplayTitle" Instead of "Name"

### ISSUE THREAD

**Issue by LuxLuma** [rikka0w0/l4d2_mission_manager#4]
Hi rikka I would like to suggest a change to the way mission names are displayed I will use Night Terror 2013 as an example.

Here is the name that is displayed in the menu below.
`"Name"		"nt2013"`
Most people will have no idea what this is.

Here is the display title.
`"DisplayTitle"	"Night Terror 2013"`
Most people will know what this is.

[nt2013.txt](https://github.com/rikka0w0/l4d2_mission_manager/files/2924588/nt2013.txt)

This would be helpful for non native english people also, this is the name they see in the addon map list.

Thanks for awesome plugin.

**Comment by rikka0w0** [comment]
Hi LuxLuma,

> This would be helpful for non native english people also, this is the name they see in the addon map list.

This is not true, the server doesn't know what version of addon map the client is using, The server can only know the language preference of clients, and then send them the localized menu items. This means all localization have to be done on the server side. If a client is using a language that is not available on the server, they will see English menu.

In the next version, I'm going to let the "DisplayTitle" be the default(English) display text. For now, on your server, you can find a file `left4dead2/addons/sourcemod/translations/missions.phrases.txt`, you can manually add map name localization here.


Thanks for your suggestion

**Comment by LuxLuma** [comment]
Hello Rikka thanks for the insight in future works and your reasoning with the DisplayTitle.
Ill do changes and wait for your update. 

Thanks 👍

**Comment by rikka0w0** [comment]
I was think about this:
Setup a web service (on Github, I think) for campaign name localization. 
The mission manager will first look for entries in the local localization files, if it cannot be found then attempt to contact a web address to see if the localized name can be resolved by the server. If all of these fail then use the map name.

How does this sounds?
